### PR TITLE
Initial Calendar UI structure

### PR DESCRIPTION
**Pull request by mwalbeck**

### CODE REVIEW

**Comment by oliveiraigorm** [comment]
Look clean!
I'm having a bug though, after clicking on new event, the popup goes to the right side of the window and I can't close it, and the right scroll of the window is glitching and doesn't work 
image

**Comment by mwalbeck** [comment]
@oliveiraigorm This might be more related to the sometimes slightly buggy positioning of the pop-up. Does it persist if you reload the page?

**Comment by oliveiraigorm** [comment]
> @oliveiraigorm This might be more related to the sometimes slightly buggy positioning of the pop-up. Does it persist if you reload the page?

Yes. But one thing to consider is that I still have the custom sidebar that is on the left, so maybe that doesn't happen with the new navbar.

**Comment by mwalbeck** [comment]
Ahh yes, that most likely messes with the width. If you go into Apps and disables it, you can check if it's still an issue.

**Comment by oliveiraigorm** [comment]
> Ahh yes, that most likely messes with the width. If you go into Apps and disables it, you can check if it's still an issue.

All working fine with the new one!

**Pull request merged**
